CREATE TABLE advertisers_statistics
    (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        data_source VARCHAR(255),
        campaign VARCHAR(255),
        daily DATE,
        clicks INTEGER,
        impressions INTEGER,
        PRIMARY KEY(id)
    );